feat: Control `animate` option for `push`, `pop`, `replace` actions
daangn/stackflow pull request #189
Opened 2022-07-07 13:01 UTC by irrationnelle

- optional 하게 다루기 위해 undefined 인 경우 false 로 간주할 수 있도록 `noAnimate` 로 명명했어요.
- `noAnimate` 가 true 인 경우에는 makeEvent 호출 시점의 eventDate 와 상관없이 항상 `transitionState` 가 `enter-done` 상태에요
- 이 스펙이 유효하여 approved 되면, 뒤이어서 replace(enter-done) 와 pop(exit-done) 에 해당하는 스펙을 추가 커밋으로 구현해요.

2022-07-10 13:52 UTC, irrationnelle commented
```
const CustomBackButton = () => {
  const {pop} = useFlow();

  return (
    <div>
      <button type="button" onClick={() => {
        pop({animate: false})
      }}>back</button>
    </div>
  )
}


const Layout: React.FC<LayoutProps> = ({ appBar, children }) => {
  return (
    <AppScreen
      appBar={{
        customBackButton: CustomBackButton,
        ...appBar,
      }}
    >
      {children}
    </AppScreen>
  );
};

export default Layout;
```

이렇게 `CustomBackButton` 을 생성하여 AppScreen 에 props 로 전달하면 `basic-ui` 를 사용하면서 animate 를 제어가 가능해요.

2022-07-10 13:57 UTC, irrationnelle commented
`useCoreActions` 에서 `eventOptions` 을 별도의 함수나 메서드 호출 없이 수작업(?)으로 option 에서 animate 를 찾아내서 할당하는데, options 의 field 가 현재는 animate 하나뿐이라 이렇게 하긴 했는데, `triggerPreEffectHook` 와 `dispatchEvent` 라는 함수 호출 사이에 끼어있으니까 흐름을 깨뜨리는 인상을 주어요. 

---

위 코멘트를 남기면서 생각해보니, PreEventHook 이 options 를 모른다는 건 플러그인 제작자 입장에서 이상하게 느껴질 수 있겠네요. triggerPreEffectHook 에 options 값도 전달해야겠어요.

2022-07-11 02:57 UTC, tonyfromundefined reviewed
어디서 추상화 layer를 끊을지가 약간 애매하네요 ㅋㅋ

`animate: false`
`skipEnterActiveState: true`

둘이 이름을 맞춰줘야하나 싶기도 하구요.

2022-07-11 02:57 UTC, tonyfromundefined commented on integrations/react/src/core/useCoreActions.ts
> +      options?: { animate?: boolean };
저는 이벤트랑 맞춰서 options로 안 묶고 그냥 `skipEnterActiveState`로 노출하는게 더 일관성 있을거같아요.

2022-07-11 02:57 UTC, tonyfromundefined commented on integrations/react/src/useActions.ts
>        },
요 layer에서 options -> skipEnterActiveState 인터페이스 변환해주고요.

2022-07-11 10:44 UTC, tonyfromundefined commented on integrations/react/src/utils/checkToSkipActiveState.ts
> +  return !options.animate
```suggestion
  return {
    skipActiveState: !options.animate,
  }
```

2022-07-11 10:44 UTC, tonyfromundefined commented on integrations/react/src/utils/checkToSkipActiveState.ts
> +  return !options.animate
named parameter 뭐 그런 글이 있었는데 까먹음... ㅠㅠ

2022-07-11 12:59 UTC, tonyfromundefined requested changes

2022-07-11 12:59 UTC, tonyfromundefined commented on integrations/react/src/useActions.ts
> +function parseActionState(options?: { animate?: boolean }) {
```suggestion
function parseActionOptions(options?: { animate?: boolean }) {
```

2022-07-11 13:07 UTC, tonyfromundefined approved these changes

2022-07-11 13:08 UTC, merged