refactor: server environment check func
daangn/stackflow pull request #337
Opened 2023-01-30 11:04 UTC by tooooo1

stackflow 여러 곳에 흩어져 있던 typeof window 코드들을 하나로 관리합니다.

기존에는 아래 4가지 파일에서 7군데가 흩어져 있었어요.
- integrations\react\src\stackflow.tsx
- extensions\plugin-basic-ui\src\basicUIPlugin.tsx
- extensions\plugin-history-sync\src\historyState.ts
- extensions\plugin-history-sync\src\historySyncPlugin.tsx

이제는 integrations/react/src/utils 안에 있는 `isBrowser.ts`와 `isServer.ts`에서 컨트롤합니다.

추가적으로 오픈소스임을 고려하여 [jsdoc - @description](https://jsdoc.app/tags-description.html)을 통해 설명을 추가했어요.

![image](https://user-images.githubusercontent.com/77133565/215459886-af86ca06-f030-4115-824f-8ed467d28f2a.png)

리팩토링 진행 후 빌드가 정상적으로 동작하는 것을 확인했습니다.

![image](https://user-images.githubusercontent.com/77133565/215459523-6fa065c5-2d1d-4b77-970b-c84efb6dd9d9.png)

해당 PR이 만들어진 이유는 #335 에서 확인하실 수 있어요.

이전에 올라온 PR이나 commit들을 꼼꼼히 보고 PR을 올렸지만 빠트린 부분이 있을 수도 있습니다 ㅠㅠ 
빠트린 부분이 있다면 알려주세요!

---

Close https://github.com/daangn/stackflow/issues/335

2023-01-30 14:10 UTC, tonyfromundefined requested changes

2023-01-30 14:10 UTC, tonyfromundefined commented on extensions/plugin-basic-ui/src/basicUIPlugin.tsx
> +import { isBrowser } from "@stackflow/react";
`isBrowser()` 는 `@stackflow/react`의 공식 기능이 아니기 때문에, 다음과 같이 공통화하는것이 더 나아요.

1. 각 패키지 내에 `./src/utils` 등 폴더에 파일로 추가 (패키지 별로 Copy & Paste)
2. 만약 중복되는 부분이 많아질것으로 예상된다면, (`./src/utils` 폴더가 무거워질것 같다면) `@stackflow/utils` 패키지로 분리해서 추가

두가지 선택지 중 저는 당장 1번이 더 나을것 같은데, 이렇게 작업해주실 수 있나요?

2023-01-31 09:53 UTC, pers0n4 commented
각 함수를 별도의 파일로 분리하는 대신 런타임과 관련된 로직들을 포함하는 하나의 파일에서 `isBrowser`와 `isServer`를 `export`하는 구조는 어떨까요?

2023-01-31 10:35 UTC, tonyfromundefined commented
> 각 함수를 별도의 파일로 분리하는 대신 런타임과 관련된 로직들을 포함하는 하나의 파일에서 `isBrowser`와 `isServer`를 `export`하는 구조는 어떨까요?

그런 구조로 간다고 하면 `is*()`인 Boolean 타입 보다는 enum을 쓰는것이 맞을거같네요.

```typescript
export function getEnvironment(): { environment: 'server' | 'client' | '%future_added_value%' } {
  return {
    environment: typeof window === 'undefined' ? 'server' : 'client'
  }
}
```

2023-01-31 14:12 UTC, tooooo1 commented
@pers0n4 
네 좋을거 같다고 동의해요! 하나의 파일에서 isBrowser와 isServer를 관리하면 좋겠지만 그것들을 관리하는 파일명을 생각하는 게 어려웠기도 하고 지금처럼 명확하게 관리해주는 것이 더 stackflow에 맞다고 생각했어요. stackflow의 코드들을 보면 지금처럼 관리해주고 있어서요.

@tonyfromundefined 
`getEnvironment()`를 보면 process.env.NODE_ENV를 return해줄 거라고 기대했는데요 혹시 지금 올려주신 enum을 쓰는 형식으로 변경해서 올릴까요? 저는 지금 코드 말씀해주신 경로 수정해서 stackflow에 입히고 싶긴 한데 tony가 원하시는 대로 반영할게요!

2023-01-31 22:15 UTC, tooooo1 commented on extensions/plugin-basic-ui/src/basicUIPlugin.tsx
> +import { isBrowser } from "@stackflow/react";
작업했어요! 이제 더이상 "@stackflow/react"에서 불러오지 않아요. 확인 부탁드려요

2023-02-01 02:27 UTC, tonyfromundefined approved these changes
충분한것 같아요! 수고하셨습니다!

2023-02-01 02:29 UTC, tonyfromundefined commented
close #335

2023-02-01 02:30 UTC, merged