refactor(plugin-history-sync): higher-order-func
daangn/stackflow pull request #340
Opened 2023-02-01 03:18 UTC by tooooo1

기존 for문을 forEach문으로 변경했어요

2023-02-01 06:35 UTC, tonyfromundefined requested changes

2023-02-01 06:35 UTC, tonyfromundefined commented on extensions/plugin-history-sync/src/historySyncPlugin.tsx
> +              ];
여기서 return을 하게되면, `overrideInitialEvents()` 함수의 return이 아니라, forEach에 넘겨준 callback 함수의 return이 되는거 같아요. 그래서 동작이 달라질 것 같습니다.

2023-02-01 08:09 UTC, tooooo1 commented on extensions/plugin-history-sync/src/historySyncPlugin.tsx
> +              ];
알려주셔서 감사합니다. 공부 열심히 한 후에 다시 한번 열심히 만들어봤어요...! 확인 부탁드립니다.

2023-02-01 09:21 UTC, tonyfromundefined commented
plugin-history-sync 쪽은 테스트 코드가 없어서, 저희 자체적으로 테스트를 좀 해봐야될거같아요. Approve & Merge 까지 시간이 조금 걸릴 것 같아서, 기다려주시면 감사하겠습니다. 기여 감사합니다~

2023-02-24 03:28 UTC, tonyfromundefined commented
@tooooo1 main 브랜치에 plugin-history-sync 관련 테스트코드가 머지되었어요~ 리베이스 받아주시면 감사하겠습니다!

2023-02-24 07:25 UTC, tooooo1 commented
@tonyfromundefined 

리베이스 했습니다!

2023-02-24 07:28 UTC, tonyfromundefined approved these changes

2023-05-31 11:57 UTC, tooooo1 commented
@tonyfromundefined update branch 했어요! 확인 부탁드려요!

2023-06-05 07:13 UTC, orionmiz requested changes

2023-06-05 07:13 UTC, orionmiz commented on extensions/plugin-history-sync/src/historySyncPlugin.tsx
> +              const template = makeTemplate(route);
```suggestion
              const template = makeTemplate(route, options.urlPatternOptions);
```

rebase 시점에 새로운 파라미터가 추가 됐어요. 반영 부탁드릴게요~

2023-06-08 02:55 UTC, orionmiz approved these changes

2023-06-08 02:56 UTC, merged