refactor(core): findTargetActivityIndexes
daangn/stackflow pull request #341
Opened 2023-02-01 08:52 UTC by tooooo1

공통적으로 사용하는 모듈들을 정의하고 재사용하는데 성공했어요.

PR 이유
- 같은 형태의 코드들의 반복이 있어 하나로 관리할 수 있을 것 같았어요.
- 하나로 관리를 하게되면 나중에 stackflow 유지보수 할 때 편리해질 것으로 예상됩니다!

2023-02-01 09:32 UTC, malangcat commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +function sortActivitiesByEventDate(a1: Activity, a2: Activity) {
suggestion: `sort`보다는 `compare`가 메소드의 동작을 더 잘 드러낸다고 생각해요.

2023-02-01 09:44 UTC, tooooo1 commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +function sortActivitiesByEventDate(a1: Activity, a2: Activity) {
엇 저도 동의해요! 수정했어요 감사합니다 Asher!

2023-02-01 09:45 UTC, tooooo1 commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +function sortActivitiesByEventDate(a1: Activity, a2: Activity) {
@malangcat 
새로고침 눌렀는데 @orionmiz 리뷰어 분이 사라졌어요..!

2023-02-01 10:09 UTC, orionmiz commented
@tooooo1 리뷰 준비되면 다시 멘션 부탁드릴게요~

2023-02-01 10:26 UTC, tooooo1 commented
@orionmiz 리뷰 준비되었어요

2023-02-01 12:02 UTC, orionmiz commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +}
`!activity.exitedBy`에 충분히 논리가 담겨있다 생각해서 굳이 함수로 분리하지는 않아도 될 거 같아요!

2023-02-01 12:54 UTC, orionmiz requested changes

2023-02-01 12:54 UTC, orionmiz commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +}
```suggestion
```

2023-02-01 12:54 UTC, orionmiz commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +    .filter(isActivityNotExited)
```suggestion
    .filter(activity => !activity.exitedBy)
```

2023-02-01 13:03 UTC, orionmiz requested changes

2023-02-01 13:08 UTC, orionmiz commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +
```suggestion
```

2023-02-01 13:14 UTC, orionmiz requested changes

2023-02-01 13:14 UTC, orionmiz commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +}
```suggestion
```

`!activity.exitedBy`에 충분한 논리가 담겨있다 생각해서 굳이 함수로 분리할 필요는 없어보여요!

2023-02-01 13:14 UTC, orionmiz commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +
```suggestion
```

2023-02-01 13:14 UTC, orionmiz commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +    .filter(isActivityNotExited)
```suggestion
    .filter(activity => !activity.exitedBy)
```

2023-02-01 18:44 UTC, tooooo1 commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +}
저도 동의합니다! `!activity.exitedBy`에 이미 충분한 논리가 담겨져 있다고 보여요. 제가 한 의도는 반복되는 코드라 컨트롤하기 쉽게, 유지 보수 때 실수를 줄여줌에 있어서 리팩터링을 진행 했는데요. @orionmiz 어떻게 생각하시는지 궁금해요

2023-02-02 02:55 UTC, orionmiz commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +}
@tooooo1 알겠습니다 👍 이 부분은 그대로 반영할테니 [공백을 제거한 커밋](https://github.com/daangn/stackflow/pull/341/commits/f4f6a0e808b0d93b37fd2e74463beaa0e96acd4c)은 Revert 부탁드릴게요~

2023-02-02 03:41 UTC, tooooo1 commented on core/src/activity-utils/findTargetActivityIndexes.ts
> +}
요청하신 [공백을 제거한 커밋](https://github.com/daangn/stackflow/pull/341/commits/f4f6a0e808b0d93b37fd2e74463beaa0e96acd4c) Revert 작업을 완료했어요.

2023-02-02 03:54 UTC, orionmiz approved these changes
기여 감사합니다!

2023-02-02 03:55 UTC, merged