docs: revise document tone
daangn/stackflow pull request #544
Opened 2024-12-13 16:11 UTC by effozen

## Motivation
While reading the official StackOverflow documentation, I noticed that the tone of the Korean translation was inconsistent and sometimes varied. To provide a unified experience for readers and enhance comprehension, I have revised the tone throughout the document. Additionally, I have adjusted some expressions to better align with the original English version.

## Changes Made
- Standardized the tone across the entire Korean documentation.
- Modified expressions to more accurately reflect the English translations.
- Corrected any awkward phrasing to improve readability and understanding.

## Additional Information
These changes aim to ensure that users have a consistent and clear experience when reading the Korean version of the documentation, making it easier to understand and follow.

2024-12-13 16:54 UTC, ENvironmentSet requested changes
I think maintaining consistency while writing documents is quite a challenging task 😀. Thank you for reviewing ours thoroughly. I've left comments on some lines that need to be revised. Could you please take a look?

2024-12-13 16:54 UTC, ENvironmentSet commented on docs/pages/api-references/plugins/plugin-google-analytics-4.ko.mdx
> +상단 코드에서 보낸 사용자 정의 GA4 이벤트의 예시에요.
Shouldn't this be "예시예요"?

2024-12-13 16:54 UTC, ENvironmentSet commented on docs/pages/api-references/plugins/plugin-google-analytics-4.ko.mdx
> +두번째 매개변수 객체는 사용자 정의 이벤트 매개변수로 전송되요.
I think this have to be "전송돼요".

2024-12-13 16:54 UTC, ENvironmentSet commented on docs/pages/api-references/plugins/plugin-history-sync.ko.mdx
> +| history           | `History` (optional)                                        | 네비게이션 상태를 관리하는 데 사용되는 사용자 정의 히스토리 객체에요. 기본적으로 브라우저나 메모리 히스토리에요. |
Same for these. It might be correct to use "-이에요" or "-예요".

2024-12-13 16:54 UTC, ENvironmentSet commented on docs/pages/api-references/plugins/plugin-history-sync.ko.mdx
> +| useHash           | `boolean` (optional)                                        | 해시 기반 라우팅을 사용할지를 결정해요. 기본값은 false에요.                                         |
I think there should be "-예요" for "false".

2024-12-13 16:54 UTC, ENvironmentSet commented on docs/pages/api-references/plugins/plugin-map-initial-activity.ko.mdx
> +| mapper  | `(url: URL) => { activityName: string; activityParams: {}; } \| null` | URL을 받아서 액티비티 이름과 매개변수가 포함된 객체를 반환하거나, 일치하는 것이 없으면 null을 반환하는 함수에요. |
Same case here!

2024-12-13 16:54 UTC, ENvironmentSet commented on docs/pages/api-references/plugins/plugin-renderer-basic.ko.mdx
> +이 플러그인은 스택 상태를 기반으로 액티비티를 기본적으로 렌더링하는 데 사용되요.
"-어-" is missing here.

2024-12-13 17:06 UTC, effozen commented
Thank you for delicate check. I've got some wrong knowledge about it, and fix what I missed.
Also, I found one file that didn't change tone, so I also revise it.

2024-12-16 05:43 UTC, ENvironmentSet requested changes

2024-12-16 05:43 UTC, ENvironmentSet commented on docs/pages/api-references/plugins/plugin-map-initial-activity.ko.mdx
> +주어진 URL을 사용하여 초기 액티비티를 매핑하는 데 사용되는 플러그인이예요.
It should be "이에요".

2024-12-16 05:43 UTC, ENvironmentSet commented on docs/pages/api-references/plugins/plugin-google-analytics-4.ko.mdx
> +filename="AdCreateButton.tsx" copy
Are there any reason for this linebreak?

2024-12-16 05:43 UTC, ENvironmentSet commented on docs/pages/api-references/plugins/plugin-stack-depth-change.ko.mdx
> +| depth           | `number`                           | 활성 액티비티 스택의 현재 깊이예요.                                      |
This must be '-예요' or '-이에요'.

2024-12-16 15:02 UTC, effozen commented on docs/pages/api-references/plugins/plugin-google-analytics-4.ko.mdx
> +filename="AdCreateButton.tsx" copy
Thank you team, I didn't notice typo. I fixed all. Really thanks.

2024-12-16 15:03 UTC, effozen commented
Team, sorry for inconvenience and really appreciate you for kind review. All fixed.

2024-12-17 01:19 UTC, ENvironmentSet approved these changes
Thank you for contribution!

2024-12-17 01:19 UTC, merged